<?php

class PxlSphere_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_sphere';
    protected $title = 'PXl Sphere';
    protected $icon = 'eicon-circle-o';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/itsapex.local\/wp-content\/themes\/apexus\/elements\/assets\/imgs\/pxl_sphere-1.webp"},"2":{"label":"Layout 2","image":"http:\/\/itsapex.local\/wp-content\/themes\/apexus\/elements\/assets\/imgs\/pxl_sphere-2.webp"}},"prefix_class":"pxl-sphere-layout"}]},{"name":"section_content","label":"Content","tab":"content","controls":[{"name":"sphere_size","label":"Sphere Size","type":"slider","size_units":["px"],"range":{"px":{"min":50,"max":2000,"step":10}},"default":{"unit":"px","size":400}},{"name":"tilt_angle","label":"Tilt Angle","type":"slider","size_units":["deg"],"range":{"deg":{"min":-90,"max":90,"step":1}},"default":{"unit":"deg","size":-30},"condition":{"layout":"2"}},{"name":"sphere_color","label":"Sphere Color","type":"color"},{"name":"rotation_type","label":"Rotation Type","type":"select","default":"y_axis","options":{"y_axis":"Y Axis (Horizontal)","x_axis":"X Axis (Vertical)","both_axis":"Both Axes"},"condition":{"layout":"1"}},{"name":"rotation_type2","label":"Rotation Type","type":"select","default":"y_axis","options":{"y_axis":"Y Axis (Horizontal)","x_axis":"X Axis (Vertical)","both_axis":"Both Axes","custom":"Custom Path","none":"No Rotation"},"condition":{"layout":"2"}},{"name":"rotation_speed","label":"Rotation Speed","type":"slider","size_units":[""],"range":{"":{"min":0.001,"max":0.02,"step":0.001}},"default":{"size":0.005}},{"name":"custom_x_speed","label":"X Axis Speed","type":"slider","size_units":[""],"range":{"":{"min":-0.02,"max":0.02,"step":0.001}},"default":{"size":0.003},"condition":{"rotation_type":["both_axis","custom"],"layout":"2"}},{"name":"custom_y_speed","label":"Y Axis Speed","type":"slider","size_units":[""],"range":{"":{"min":-0.02,"max":0.02,"step":0.001}},"default":{"size":0.005},"condition":{"rotation_type":["both_axis","custom"],"layout":"2"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'sphere','apexus-sphere' );
}