<?php

class PxlBreadcrumb_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_breadcrumb';
    protected $title = 'PXL Breadcrumb';
    protected $icon = 'eicon-navigation-horizontal';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"\\/wp-content\\/themes\/apexus\/elements\/assets\/layout-image\/pxl_fancy_box-1.jpg"}}}]},{"name":"content_section","label":"Style","tab":"style","controls":[{"name":"text_align","label":"Alignment","type":"choose","control_type":"responsive","options":{"left":{"title":"Start","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"right":{"title":"End","icon":"eicon-text-align-right"}},"selectors":{"{{WRAPPER}} .pxl-breadcrumb":"text-align: {{VALUE}}; justify-content: {{VALUE}};"}},{"name":"brc_color","label":"Text Color","type":"color","selectors":{"{{WRAPPER}} .pxl-breadcrumb, .pxl-breadcrumb .br-item":"color: {{VALUE}} !important;","{{WRAPPER}} .pxl-breadcrumb.hide-underline .br-item .br-text::after":"background-color: {{VALUE}};"}},{"name":"link_color","label":"Link Color","type":"color","selectors":{"{{WRAPPER}} .pxl-breadcrumb a":"color: {{VALUE}} !important;"}},{"name":"link_color_hover","label":"Link Color Hover","type":"color","selectors":{"{{WRAPPER}} .pxl-breadcrumb a:hover":"color: {{VALUE}} !important;"}},{"name":"selected_icon","label":"Divider Icon","type":"icons"},{"name":"icon_size","label":"Icon Size(px)","type":"slider","range":{"px":{"min":15,"max":300}},"selectors":{"{{WRAPPER}} .pxl-breadcrumb .pxli":"font-size: {{SIZE}}{{UNIT}} !important;","{{WRAPPER}} .pxl-breadcrumb svg":"width: {{SIZE}}{{UNIT}} !important;"}},{"name":"icon_color","label":"Icon Color","type":"color","selectors":{"{{WRAPPER}} .pxl-breadcrumb .br-divider":"color: {{VALUE}};"}},{"name":"brc_typography","label":"Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-breadcrumb, {{WRAPPER}} .pxl-breadcrumb a, {{WRAPPER}} .pxl-breadcrumb .br-item, {{WRAPPER}} .pxl-breadcrumb .br-divider, {{WRAPPER}} .pxl-breadcrumb .br-item"},{"name":"btn_padding","label":"Padding","type":"dimensions","size_units":["px"],"selectors":{"{{WRAPPER}} .pxl-breadcrumb .br-divider":"padding: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"},"control_type":"responsive"}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}