<?php

class PxlImageLanding_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_image_landing';
    protected $title = 'PXL Image Landing';
    protected $icon = 'eicon-image';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Layout","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"\\/wp-content\\/themes\/apexus\/elements\/assets\/layout-image\/pxl_image_landing-1.jpg"}}}]},{"name":"content_section","label":"Content","tab":"content","controls":[{"name":"selected_image","label":"Image","type":"media"},{"name":"title_text","label":"Title Text","type":"text","default":"Homepage"},{"name":"link_type","label":"Link Type","type":"select","options":{"url":"URL","page":"Existing Page"},"default":"url"},{"name":"link","label":"Link","type":"url","placeholder":"https:\/\/your-link.com","condition":{"link_type":"url"},"default":{"url":"#"}},{"name":"page_link","label":"Existing Page","type":"select2","options":{"7393":"Lading Page","6607":"Home 5","5544":"Home 4","4286":"Home 3","2761":"Home 2","1849":"About Us","1776":"Career","1232":"Services Grid","1033":"Portfolio","765":"Coming Soon","639":"404 Errer","593":"FAQs","470":"Contact","452":"Blog Left Sidebar","161":"Home 1"},"condition":{"link_type":"page"},"multiple":false,"label_block":true}]},{"name":"style_section","label":"Style","tab":"content","controls":[{"name":"border_color","label":"Border Color","type":"color","selectors":{"{{WRAPPER}} .pxl-image-landing .image-wrap":"border-color: {{VALUE}};"}},{"name":"border_hover_color","label":"Border Hover Color","type":"color","selectors":{"{{WRAPPER}} .pxl-image-landing:hover .image-wrap":"border-color: {{VALUE}};"}},{"name":"title_typography","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-image-landing .image-title"},{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-image-landing .image-title":"color: {{VALUE}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}